export const ADD_EXPENSE = 'ADD_EXPENSE';
export const SET_EXPENSES = 'SET_EXPENSES';
export const ADD_FILTER_EXPENSE = 'ADD_FILTER_EXPENSE';
export const SHOW_ADD_EXPENSE_FORM = 'SHOW_ADD_EXPENSE_FORM';
export const HIDE_ADD_EXPENSE_FORM = 'HIDE_ADD_EXPENSE_FORM';